version: "3.8"

services:
  booking:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  database:
    image: 'mariadb'
    restart: always
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: php_db
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8998:80'
    environment:
      - PMA_ARBITRARY=1

volumes:
  data: